server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://192.168.1.113/identity_service"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  signerKey: "eZgTYQHdUBZ4ld2x22JFHxR6ih20LXl8cCS97/ad4t4PbURY40+ieJX5T67H/bHh"
